global:
  resolve_timeout: 5m

route:
  receiver: "simulation"

receivers:
  - name: "simulation"
    email_configs:
      - to: "sreejapanyala24@gmail.com"
        send_resolved: true
    slack_configs:
      - api_url: "https://hooks.slack.com/services/T000/B000/FAKE"
        channel: "#alerts"
        send_resolved: true